branch-defaults:
  master:
    environment: onlylocalfood-api
  deploy-connection-to-db:
    environment: onlylocalfood-api
environment-defaults:
  onlylocalfood-api:
    branch: null
    repository: null
global:
  application_name: onlylocalfood
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Node.js running on
    64bit Amazon Linux/4.0.1
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
