branch-defaults:
  master:
    environment: onlylocalfoods-api
    group_suffix: null
environment-defaults:
  help:
    branch: null
    repository: null
global:
  application_name: onlylocalfood-api
  branch: null
  default_ec2_keyname: null
  default_platform: node.js
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
